" Basic
set number
set cursorline
set showcmd
set ruler

" Search
set ignorecase
set smartcase
set incsearch
set hlsearch

" Indent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent

" Display
syntax enable
filetype plugin indent on

" Editing
set backspace=indent,eol,start
set hidden
set mouse=a

" Convenience
set scrolloff=5
set wildmenu

" Files
set encoding=utf-8
set nobackup
set nowritebackup
set noswapfile

" Clipboard
" Vim is built with +clipboard, so y/d/p share the macOS pasteboard directly.
" On macOS the * and + registers are the same pasteboard.
set clipboard=unnamed

" Key-mapping
inoremap jj <Esc>
vnoremap jj <Esc>

" Normal mode: block cursor
" Insert mode: vertical bar cursor
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
